import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import '../globals.css'
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar";
import { getServerSession } from "@/lib/get-session";
import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import { redirect, unauthorized } from "next/navigation";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();
  const user = session?.user;

  if(!user) {
    redirect('/signin');
  }


  return (
    <main>
      <div className="min-h-full flex flex-col font-intel">
        <Navbar user={user} />
        {children} 
        <Toaster richColors />
      </div>
    </main>

  );

}